### ISSUE TITLE
Run in zammad docker container?

### ISSUE THREAD

**Issue by seljuck** [minvws/nl-rdo-zammad-api-export#201]
I see in the readme.md file that you mention the Zammad docker-compose setup. Does that mean you are recommending to add this tool to the zammad docker container?

If not, do you have a docker container for this tool?

Thanks,
Daniel

**Comment by ricklambrechts** [comment]
We have updated the readme. It is not recommended to run Zammad in Docker for production usage.

This is a script that you can run where there PHP8.0 and composer available. It is possible to create a docker image with this tool but this is currently not on our planning to create this. If someone create a PR for this we can review it.

**Comment by seljuck** [comment]
Thank you for the answer.
