### ISSUE TITLE
Add feature to get single ticket

### ISSUE THREAD

**Issue by seljuck** [minvws/nl-rdo-zammad-api-export#202]
Would it be possible to add the ability to export a single ticket? That could be called with just the Ticket ID?

Thanks

**Comment by ricklambrechts** [comment]
The export script also has the ability to export Zammad tickets based on a search query.
This uses the [advanced search feature](https://user-docs.zammad.org/en/latest/advanced/search.html#advanced-search) of Zammad.

```sh
php zamex.php export <path> --search "number:1234"
```

**Comment by seljuck** [comment]
Perfect!

Thanks for the answer.
